#!/bin/bash

TOP_LEVEL=$(git rev-parse --show-toplevel)
. $TOP_LEVEL/cw-ansible.cfg


install_deps() {
    sudo apt-get update
    sudo apt-get install --yes --no-install-recommends \
	 git rsync ca-certificates python-jinja2 python-yaml
}


install_deps
$TOP_LEVEL/scripts/bootstrap-ansible
$TOP_LEVEL/scripts/bootstrap-cw-ansible

