#!/bin/bash

TOP_LEVEL=$(git rev-parse --show-toplevel)
. $TOP_LEVEL/cw-ansible.cfg


packages='git rsync ca-certificates python-jinja2 python-yaml'


apt_get_update() {
    local lastup="$(( (`date +%s` - `stat -L --format %Y /var/lib/apt/lists`) > (30*60) ))"
    if test $lastup = "0"; then
	sudo apt-get update
    fi
    
}


install_deps() {
    apt_get_update
    sudo apt-get install --yes --no-install-recommends \
	 git rsync ca-certificates python-jinja2 python-yaml
}


install_deps
$TOP_LEVEL/scripts/bootstrap-ansible
$TOP_LEVEL/scripts/bootstrap-cw-ansible

