#!/bin/bash


DEVELOPER=~/Developer

ANSIBLE_PREFIX=$DEVELOPER/ansible
ANSIBLE_SRC=$ANSIBLE_PREFIX/ansible
ANSIBLE_VERSION=${1:devel}

_OLD_CWD=$(pwd)
TOP_LEVEL=$(git rev-parse --show-toplevel)

install_deps() {
    sudo apt-get update
    sudo apt-get install --yes --no-install-recommends \
	 git rsync ca-certificates python-jinja2 python-yaml
}


install_ansible() {
    mkdir -p $ANSIBLE_PREFIX
    cd  $ANSIBLE_PREFIX
    if ! test -d $ANSIBLE_SRC; then
        git clone --recursive https://github.com/ansible/ansible.git
    fi
    cd ansible
    git checkout $ANSIBLE_VERSION
    cd $_OLD_CWD
}

install_cw_ansible() {
    . $ANSIBLE_SRC/hacking/env-setup
    cd $TOP_LEVEL
    ansible-playbook -i localhost, bootstrap-cw-ansible.yml
    cd $_OLD_CWD
}

install_deps
install_ansible
install_cw_ansible

cat <<EOF
Before invoking ansible you should setup the haking environment:

  . $ANSIBLE_SRC/hacking/env-setup
EOF
